# Generated by Django 3.2.8 on 2021-10-15 16:16

from django.db import migrations, models
import typing


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211015_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='metadata',
            field=models.JSONField(verbose_name=typing.DefaultDict),
        ),
    ]
